### ISSUE TITLE
Passive Credit Timer

### ISSUE THREAD

**Issue by TricycleRaptor** [TricycleRaptor/CaptureTheFlag-Redux#4]
The passive timer designed to award credits on a given amount of time does not currently work properly. There is a current implementation that may work, but more testing is required.

**The new implementation can be found on line 858 in init.lua**

To-do:
1.) Get timer working for all clients
2.) Find a better area of implementation other than a one-time call when the round starts, in the event that players join after the fact.

**Comment by TricycleRaptor** [comment]
Code can now be found on line 865 of init.lua

**Comment by TricycleRaptor** [comment]
Timer works for everyone except the host.

**Comment by Seth1466** [comment]
Try dabbing on it.

**Comment by TricycleRaptor** [comment]
Timer works completely.
